name: Print Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build
      
  hello-world:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v2

      
    - name: Run script locally
      run: bash ./.github/workflows/run.sh

      
    - name: Print Secret
      env:
        FIRSTSTEPSREPOSITORYSECRET: ${{ secrets.FIRSTSTEPSREPOSITORYSECRET }}
      run: echo $FIRSTSTEPSREPOSITORYSECRET

      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2222
        script: echo “Hello World”

      
    - name: Execute run.sh on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2222
        script: bash /home/${{ secrets.USERNAME }}/run.sh
